user:
  name_length: 50
  email_length: 255
  password_length: 6
  avatar_size: 80
  avatarsizeshow: 50
  checked: "1"
  expiredtime: 2
  avatarsize: 30
micropost:
  number_maximum: 140
  number_micropost_html: 50
  picture_size: 5
user_info_html:
  number_size: 50
  